### PR TITLE
DO NOT MERGE. WORK IN PROGRESS Tipsi stripe incorporated with all our most recent changes!

### PR DESCRIPTION
**Pull request by Justinfan827**
Buildable version of the user app with tipsi stripe

### CODE REVIEW

**Comment by Justinfan827** [comment]
@TheWillMundy  @amyhuyen98  I think there needs to be a way to incorporate persistent navigation with logging in. I.e. when the user refreshes the simulator on the createAccountScreen, the user should still be on the createAccountScreen and their netID should still be there.

**Comment by Justinfan827** [comment]
@TheWillMundy @amyhuyen98 Also, I currently get this error when submitting the test credit card '4242 4242 4242 4242' 

screen shot 2019-03-05 at 9 26 00 pm

@jlt10 any ideas what's going on?

**Comment by TheWillMundy** [comment]
> @TheWillMundy @amyhuyen98 Also, I currently get this error when submitting the test credit card '4242 4242 4242 4242'
> 
> screen shot 2019-03-05 at 9 26 00 pm
> 
> @jlt10 any ideas what's going on?

This is a backend issue although @amyhuyen98 didn't you end up figuring out a solution at the end of Saturday?

**Comment by amyhuyen98** [comment]
I think that had to do with us trying to create customer id pairs on stripe. I'm pretty sure it works with the fake tokens "token_mastercard" and "token_visa" but I'm not really sure why

**Comment by TheWillMundy** [comment]
> @TheWillMundy @amyhuyen98 I think there needs to be a way to incorporate persistent navigation with logging in. I.e. when the user refreshes the simulator on the createAccountScreen, the user should still be on the createAccountScreen and their netID should still be there.

Are you sure that is the intended behavior? Refreshing the simulator essentially recompiles the application... I think the intended behavior would be to go back to the start since it's possible that changes were made to the application, no? What we should actually be focusing on is bypassing the login screen after the splash screen once a user has logged in during a prior session.

**Comment by willsu88** [comment]
> > @TheWillMundy @amyhuyen98 Also, I currently get this error when submitting the test credit card '4242 4242 4242 4242'
> > screen shot 2019-03-05 at 9 26 00 pm
> > @jlt10 any ideas what's going on?
> 
> This is a backend issue although @amyhuyen98 didn't you end up figuring out a solution at the end of Saturday?

My app builds now on my computer. I can log in and log out successfully. I also get the same error Will is getting.

**Comment by Justinfan827** [comment]
@TheWillMundy  @amyhuyen98 I think I found out why we're getting errors with the tokens. When createUserHandler() is called, a single token is generated. However on the backend createUser call, we use that single token when creating customers for The Hoot and East West.

**Comment by Justinfan827** [comment]
i.e. we have multiple vendors with different keys. The tokens generated by a particular key is unique to that key and cant be recognized by other keys. I.e in payment-request.js: 

 stripe.setOptions({
                        publishableKey: 'pk_test_AFqSBwnwrS3AInWfxCylFcyk'
                });

Using this key will only generate a token valid for whichever vendor has this stipe API key.

**Pull request merged**
